#------------------------------------------------------------------------------
#
# Copyright GBM GRUPO BURSÁTIL MEXICANO, S.A DE C.V., CASA DE BOLSA
#
# File: am_accounts_table.yml
# Purpose: Database Infrastructure as Code for Serverless Deployment of Account Manager
#------------------------------------------------------------------------------

Resources:
  accountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      KeySchema:
        - AttributeName: partition_key
          KeyType: HASH
        - AttributeName: search_resource
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: partition_key
          AttributeType: S
        - AttributeName: search_resource
          AttributeType: S
        - AttributeName: org_corp
          AttributeType: S
        - AttributeName: filters
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: filters-GSI
          KeySchema: 
          - AttributeName: org_corp
            KeyType: HASH
          - AttributeName: filters
            KeyType: RANGE
          Projection: 
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TableName: am-accounts-test